[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  included_files = [".next/server/**/*.js"]
  external_node_modules = ["next"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next_api_:splat"
  status = 200
  force = true

# Ensure `results` page can handle query parameters properly
[[redirects]]
  from = "/results"
  to = "/.netlify/functions/next_results"
  status = 200
  force = true

# Ensure place pages work for SSR
[[redirects]]
  from = "/place/*"
  to = "/.netlify/functions/next_place_:splat"
  status = 200
  force = true
