[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  # Enable CSS optimization
  NEXT_OPTIMIZE_CSS = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"


# Handle results page with query parameters
[[redirects]]
  from = "/results"
  to = "/results"
  status = 200
  force = true
  query = {category = ":category", neighborhoods = ":neighborhoods"}

# Fallback for results with any query parameters
[[redirects]]
  from = "/results"
  to = "/results"
  status = 200
  force = true

# Handle place pages
[[redirects]]
  from = "/place/*"
  to = "/place/[...params]"
  status = 200
  force = true

# Handle static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Final fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true