[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://newyorkcurated.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"