[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  # Handle results page with query parameters
[[redirects]]
  from = "/results"
  to = "/results"
  status = 200
  force = true
  query = {category = ":category", neighborhoods = ":neighborhoods"}

# Fallback for results with any query parameters
[[redirects]]
  from = "/results"
  to = "/results"
  status = 200
  force = true

  [[redirects]]
  from = "/place/*"
  to = "/place/:splat"
  status = 200
  force = true