[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_USE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/nextjs-server/api/:splat"
  status = 200

# Handle static assets
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Handle results page with query parameters
[[redirects]]
  from = "/results"
  to = "/.netlify/functions/nextjs-server/results"
  status = 200
  force = true
  query = {category = ":category", neighborhoods = ":neighborhoods"}

# Handle place pages
[[redirects]]
  from = "/place/*"
  to = "/.netlify/functions/nextjs-server/place/:splat"
  status = 200

# Final catch-all
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server/:splat"
  status = 200
  force = true