[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle all routes through Next.js
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextServer"
  status = 200
  force = true