[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://newyorkcurated.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  # Handle results page with query parameters
[[redirects]]
  from = "/results"
  to = "/results"
  status = 200
  force = true
  query = {category = ":category", neighborhoods = ":neighborhoods"}

# Fallback for results with any query parameters
[[redirects]]
  from = "/results"
  to = "/results"
  status = 200
  force = true

  [[redirects]]
  from = "/place/*"
  to = "/place/:splat"
  status = 200
  force = true