[build]
  command = "npm run build"
  publish = ".netlify/functions-internal"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle dynamic routes for places
[[redirects]]
  from = "/place/:neighborhood/:name"
  to = "/.netlify/functions/place"
  status = 200
  force = true

# Handle results page with query parameters
[[redirects]]
  from = "/results"
  to = "/.netlify/functions/results"
  status = 200
  force = true
  query = {category = ":category", neighborhoods = ":neighborhoods"}

# Final fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true